minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@shun-shobon/style-guide"

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

saveExact: true

strictDepBuilds: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - reselect@5.1.1
  - semver@6.3.1
